print('What is your name?')
myName = input()
print('Hello ' + myName)
print('The length of your name is:')
print(len(myName))
print('What is your age?')
myAge = input()
print('you will be '+ str(int(myAge) + 1) + ' in a year.')
